//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ParkingSlotNumber { get; set; }
        public string Name { get; set; }
        public string VehicleNumber { get; set; }
        public string Phone { get; set; }
        public string UID { get; set; }
        public string ParkingTime { get; set; }
    }
}
